### ISSUE TITLE
Error Reading Photos (slice step cannot be zero)

### ISSUE THREAD

**Issue by mjc440** [weegreenblobbie/rank_photos#2]
Have you encountered an error "slice step cannot be zero" when trying to read photos in?  The code will run without error when I provide an empty photo directory, but errors when i provide a directory that contains either jpg or png files.

**Comment by weegreenblobbie** [comment]
do you have a backtrace?

**Comment by mjc440** [comment]
See below.  FYI, my level of python familiarity is near zero so this may be a very simple problem.

Macintosh-7:rank_photos-master emilymadden$ python rank_photos.py /Users/emilymadden/rank_photos-master/rings
Reading in photos and downsampling ...Traceback (most recent call last):
  File "rank_photos.py", line 489, in <module>
    if __name__ == "__main__": main()
  File "rank_photos.py", line 433, in main
    table.add_photo(f)
  File "rank_photos.py", line 269, in add_photo
    self._photos[filename] = Photo(filename)
  File "rank_photos.py", line 44, in __init__
    self._read_and_downsample()
  File "rank_photos.py", line 121, in _read_and_downsample
    data = data[ 0:M:step, 0:N:step, :]
ValueError: slice step cannot be zero

**Comment by weegreenblobbie** [comment]
Okay I just pushed a fix.  Try pulling it down.

**Comment by mjc440** [comment]
Different error this time.  Appreciate the help!

Macintosh-7:rank_photos-master emilymadden$ python rank_photos.py rings
Reading in photos and downsampling ...Traceback (most recent call last):
  File "rank_photos.py", line 489, in <module>
    if __name__ == "__main__": main()
  File "rank_photos.py", line 433, in main
    table.add_photo(f)
  File "rank_photos.py", line 269, in add_photo
    self._photos[filename] = Photo(filename)
  File "rank_photos.py", line 44, in __init__
    self._read_and_downsample()
  File "rank_photos.py", line 131, in _read_and_downsample
    r = str(tags['Image Orientation'])
KeyError: 'Image Orientation'

**Comment by weegreenblobbie** [comment]
I pushed another fix

**Comment by mjc440** [comment]
That worked.  Thanks!
