### ISSUE TITLE
I can't get the gui to open.

### ISSUE THREAD

**Issue by siddo0sidddo** [weegreenblobbie/rank_photos#5]
I run the command and I get this:

Reading in photos and downsampling ... done!

Then a few seconds later I get this:

Final Ranking:
Rank    Score    Matches    Win %    Filename

The window to vote never appears.

**Comment by siddo0sidddo** [comment]
I think I figured it out, it looks like matplotlib only works with python 3.6 or higher, but your code only works with python 2.7.

**Comment by Kataphractoi** [comment]
can you tell me how you fixed it?
My code behaves like: 
Reading in photos and downsampling ... done!
(fakepath)\rank_photos.py:310: UserWarning: you are shuffling a 'dict_keys' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(keys)
Final Ranking:
Rank    Score    Matches    Win %    Filename

again the window to vote never appears either.

**Comment by weegreenblobbie** [comment]
This repo needs some TLC.

**Comment by weegreenblobbie** [comment]
I pushed updates that work for me with python 3.10.1
