### ISSUE TITLE
Software bugs 

### ISSUE THREAD

**Issue by Kataphractoi** [weegreenblobbie/rank_photos#7]
ln 485: print needs () parentheses. 
ln 490: print needs () parentheses.
[unsure of fix]: ln 308 Shortened error message: File "fakepath\rank_photos.py", line 308, in rank_photos
    for i in xrange(n_iterations):
NameError: name 'xrange' is not defined. Did you mean: 'range'?

Great stuff though, cheers.

**Comment by weegreenblobbie** [comment]
Should be fixed.
